<?php

use Illuminate\Database\Seeder;
use App\notas_values;
class notas_valuesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Bimestre 1
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '1';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '2';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '3';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '4';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '5';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '6';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '7';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '8';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '9';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '10';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '11';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '12';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '13';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '14';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '15';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '1';
        $periodo->save();

        //Bimestre 2
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '1';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '2';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '3';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '4';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '5';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '6';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '7';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '8';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '9';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '10';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '11';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '12';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '13';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '14';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '15';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '2';
        $periodo->save();

        //Bimestre 3
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '1';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '2';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '3';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '4';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '5';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '6';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '7';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '8';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '9';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '10';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '11';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '12';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '9';
        $periodo->nota_structures_id  = '13';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '14';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '10';
        $periodo->nota_structures_id  = '15';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '3';
        $periodo->save();

        //Bimestre 4
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '1';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '2';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '3';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '4';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '6';
        $periodo->nota_structures_id  = '5';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '5';
        $periodo->nota_structures_id  = '6';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '5';
        $periodo->nota_structures_id  = '7';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '6';
        $periodo->nota_structures_id  = '8';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '9';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '10';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '6';
        $periodo->nota_structures_id  = '11';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '8';
        $periodo->nota_structures_id  = '12';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '13';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '6';
        $periodo->nota_structures_id  = '14';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
        $periodo = new notas_values();
        $periodo->nota = '7';
        $periodo->nota_structures_id  = '15';
        $periodo->alumno_id  = '1';
        $periodo->periodos_rangos_id  = '4';
        $periodo->save();
    }
}
